version: 2

defaults: &defaults
    working_directory: ~/workspace
    docker:
        - image: circleci/node:8.11.4

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Install dependencies
                  command: yarn
            - run:
                  name: Build
                  command: yarn build
            - save_cache:
                  key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/workspace/node_modules
            - persist_to_workspace:
                  root: .
                  paths:
                      - .
    test:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Test
                  command: yarn test
    release:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publish package
                  command: npm publish
workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                  filters:
                      tags:
                          only: /.*/
            - test:
                  requires:
                      - build
                  filters:
                      tags:
                          only: /.*/
            - release:
                  requires:
                      - test
                  filters:
                      branches:
                          only: master
                      tags:
                          only: /^v[0-9]+(\.[0-9]+){2}/
